services:
  postgres:
    image: timescale/timescaledb-ha:pg18.4-ts2.28.2
    container_name: ${POSTGRES_CONTAINER_NAME:-staging-postgres}
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    env_file:
      - .env
    volumes:
      - ${POSTGRES_MOUNT_PATH:-./data}:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
