services:
  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME:-staging-redis}
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-16379}:6379"
    env_file:
      - .env
    volumes:
      - ${REDIS_MOUNT_PATH:-./data}:/data
    networks:
      - default
